### ISSUE TITLE
Review on slides to Greg

### ISSUE THREAD

**Issue by yipengsun** [yipengsun/talks#3]
@manuelfs I've updated the slides ([latest](https://github.com/yipengsun/talks/releases/latest)). Please comment on the slides.

**Comment by manuelfs** [comment]
Nice slides. Here you have my comments
* Title “Investigating the efficiency increase in Run 2 data"
* 2: "Repeat and possibly improve Phoebe’s” → “Update Greg/Phoebe’s"
* 2: Let us focus on the efficiency increase, which is easier to talk about. Thus the last bullets would reference the factor ~3 higher efficiency in Run 2
* 3: Move here the plot from slide 7 and use the numbers of event from that plot which we trust more. 
* 4: Can you highlight the stripping, trigger, and total ratio lines? 
* 4: Add MC to title
* 5: “despite additional HLT requirement and a harder Sum(pT) cut"
* 5: "L0 unexpectedly more efficient"
* 5: “Factor of 2.48 in MC close to 3.07 seen in data"
* 5-6: Add a slide summarizing what you found for the L0 paths. The most important lines are the ones I copied here https://github.com/umd-lhcb/rdx-run2-analysis/issues/2#issuecomment-624796366, although you should add a `L0Global_TIS || L0Hadron_TOS” row with a 1.224 double ratio to show that they overlap a lot
* 6: If you want to keep that table you need to add a row before IsoBDT with the number of events and cuts applied before IsoBDT, so that it is clear what the relative ~65% are with respect to. Move it after slide 3
* 7: Remove slide, this is now our nominal data plot and should go into slide 3
* 9: I think the conclusions more accurately are
    * Larger efficiency increase in Run 2 than expected
    * It looks like it could be due to higher trigger and stripping efficiencies due to new lines and harder kinematics
        * Is this plausible?
        * Trying to confirm this by producing ntuples without full stripping cuts

**Comment by yipengsun** [comment]
I forgot to remove the subtitle. Already fixed than. Any other suggestions?

**Comment by yipengsun** [comment]
BTW, I reviewed the _Refit 𝐵̄0 decay tree_ and _After DaVinci_ entry, and they agree with `output-*.yml`.

**Comment by yipengsun** [comment]
Total: 5796, duplicate: 597, duplicate rate: 10.300207039337474%

**Comment by yipengsun** [comment]
@manuelfs I've updated the slides yet again. Please take a look at the latest (0.5.9) slides.
